{% set version = "3.3.1" %}

package:
  name: social-auth-core
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/s/social-auth-core/social-auth-core-{{ version }}.tar.gz
  sha256: 9889cab04fb94f3a66217fed2556e078d2571937b139a13d31c4bf2658128807

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python
    - pip
  run:
    - python
    - cryptography >=1.4
    - oauthlib >=1.0.3
    - pyjwt >=1.4.0
    - requests-oauthlib >=0.6.1
    - requests >=2.9.1
    - six >=1.10.0
    - python-openid >=2.2.5  # [py2k]
    - unidecode >=1.1.1  # [py2k]
    - defusedxml >=0.5.0rc1  # [py3k]
    - python3-openid >=3.0.10  # [py3k]
    - unidecode >=1.0.23  # [py3k]

test:
  imports:
    - social_core
    - social_core.backends
    - social_core.pipeline

about:
  home: https://github.com/python-social-auth/social-core
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Python social authentication made simple

extra:
  recipe-maintainers:
    - ocefpaf
