{% set version = "4.8.0" %}

package:
  name: social-auth-core
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/s/social-auth-core/social_auth_core-{{ version }}.tar.gz
  sha256: d355047d9d6d2caf39990909a585a51d90cc8fd55a897b6180bf69855237766c

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=78.0.2
    - pip
  run:
    - python >={{ python_min }}
    - cryptography >=1.4
    - defusedxml >=0.7.1
    - oauthlib >=3.3.1
    - pyjwt >=2.10.1
    - python3-openid >=3.2.0
    - requests-oauthlib >=2.0.0
    - requests >=2.32.5

test:
  imports:
    - social_core
    - social_core.backends
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}


about:
  home: https://github.com/python-social-auth/social-core
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Python social authentication made simple

extra:
  recipe-maintainers:
    - ocefpaf
