{% set version = "4.5.6" %}

package:
  name: social-auth-core
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/s/social-auth-core/social_auth_core-{{ version }}.tar.gz
  sha256: 14753d4cf870b820918729ce8a2dfe51f332075528fb13bed908701a8486da80

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >={{ python_min }}
    - cryptography >=1.4
    - defusedxml >=0.5.0rc1
    - oauthlib >=1.0.3
    - pyjwt >=2.0.0
    - python >={{ python_min }}
    - python3-openid >=3.0.10
    - requests >=2.9.1
    - requests-oauthlib >=0.6.1


test:
  imports:
    - social_core
    - social_core.backends
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}


about:
  home: https://github.com/python-social-auth/social-core
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Python social authentication made simple

extra:
  recipe-maintainers:
    - ocefpaf
