{% set version = "4.5.0" %}

package:
  name: social-auth-core
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/s/social-auth-core/social-auth-core-{{ version }}.tar.gz
  sha256: 3d4154f45c0bacffe54ccf4361bce7e66cf5f5cd1bb0ebb7507ad09a1b07d9d9

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3
    - pip
  run:
    - python >=3
    - cryptography >=1.4
    - defusedxml >=0.5.0rc1
    - oauthlib >=1.0.3
    - pyjwt >=2.0.0
    - python
    - python3-openid >=3.0.10
    - requests >=2.9.1
    - requests-oauthlib >=0.6.1


test:
  imports:
    - social_core
    - social_core.backends
  commands:
    - pip check
  requires:
    - pip


about:
  home: https://github.com/python-social-auth/social-core
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Python social authentication made simple

extra:
  recipe-maintainers:
    - ocefpaf
